//*************************************************************************/
//
// NAME :   DvdExRepository_i.hh 
// VERSION: omniORB 4 / Mico 2.3
//
// Class implementing interface as POA object.
//
//***************************************************************************/

#ifndef __DvdExRepository_hh__
#define __DvdExRepository_hh__

// Need to include the definition of the IDL C++ class generated
// from the DvdExRepository interface by the IDL compiler.

#include "DvdEx.hh"

// DvdExRepository_i uses the POA approach to indicate that it implements
// interface DvdExRepository.  That is, it inherits from the 
// POA_DvdEx::DvdExRepository class generated by the IDL compiler.

class DvdExRepository_i : public virtual POA_DvdEx::DvdExRepository,
public PortableServer::RefCountServantBase {
    CORBA::Long m_currentMaxProviderId;
    CORBA::Long m_currentMaxMediaId;

    CORBA::Short m_MaxMediaNo;
    CORBA::Short m_MaxProviderNo;

    DvdEx::DvdExMedia** media;
    DvdEx::DvdExProvider** provider;

    DvdEx::DvdExMedia* defaultEmptyMedia;
    DvdEx::DvdExProvider* defaultEmptyProvider;

public:
    // ctor
    DvdExRepository_i(CORBA::Short maxMediaNo, CORBA::Short maxProviderNo);
    // dtor
    virtual ~DvdExRepository_i();

    // functions corresponding to the two IDL readonly attributes.
    virtual CORBA::Long currentMaxProviderId();
    virtual CORBA::Long currentMaxMediaId();

    // virtual functions
    virtual DvdEx::DvdExMediaSeq* getMediaYoungerThan(CORBA::Short);
    virtual DvdEx::DvdExMediaSeq* getMediaOfType(DvdEx::Genre);
    virtual DvdEx::DvdExMedia* getMedia(CORBA::Long);
    virtual DvdEx::DvdExMediaSeq* getMediaAvailable();
    virtual void delMedia(CORBA::Long);
    virtual void addMedia(const DvdEx::DvdExMedia&);

    // virtual DvdEx::DvdExProviderSeq* DvdExRepository_i::getProviders();
    virtual DvdEx::DvdExProviderSeq* getProviders();
    virtual DvdEx::DvdExProvider* getProvider(CORBA::Long);
    virtual void delProvider(CORBA::Long);
    virtual void addProvider(const DvdEx::DvdExProvider&);

    virtual void save();
};

#endif






